// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGdhLQIAUWAw45C1x2bkDC4L4hUHW20Y',
    appId: '1:407721278683:web:77b5ebdaa484cbfe80e0fe',
    messagingSenderId: '407721278683',
    projectId: 'notifi-466bc',
    authDomain: 'notifi-466bc.firebaseapp.com',
    storageBucket: 'notifi-466bc.appspot.com',
    measurementId: 'G-VTS51PG9FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNja6JVZJu1HAiXG00gB3PG9i4U0L-QuU',
    appId: '1:407721278683:android:37b9b4ed058ba74e80e0fe',
    messagingSenderId: '407721278683',
    projectId: 'notifi-466bc',
    storageBucket: 'notifi-466bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5nuTw2Q1RLIdvpNHPsp64YjTGz6LizwQ',
    appId: '1:407721278683:ios:ad4d8cb82f8b775c80e0fe',
    messagingSenderId: '407721278683',
    projectId: 'notifi-466bc',
    storageBucket: 'notifi-466bc.appspot.com',
    iosClientId: '407721278683-9tavg9d3nckgnclmqvb11rh5ceorm263.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5nuTw2Q1RLIdvpNHPsp64YjTGz6LizwQ',
    appId: '1:407721278683:ios:9a6003fa4c6b88be80e0fe',
    messagingSenderId: '407721278683',
    projectId: 'notifi-466bc',
    storageBucket: 'notifi-466bc.appspot.com',
    iosClientId: '407721278683-0va1borkcavqtjk1gidtr2abvsji7vo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
